#!/usr/bin/env bash
# ==============================================================================
#  StreamPilot — 100% FREE always-on server installer
#  ---------------------------------------------------
#  Target : an "Always Free" VPS (Oracle Cloud, or any Ubuntu box you own).
#  Does   : installs Node 20 + Docker, clones the app, writes .env from your
#           Appwrite/YouTube keys, points the domain, and starts the service.
#
#  Usage:
#    # 1. Fill this in (or paste them when asked interactively):
#    export SP_EMAIL="you@example.com"
#    export SP_DOMAIN="streampilot.example.com"      # optional — skip for IP-only
#    export SP_APPWRITE_PROJECT="6aaeab640039b9e4c8eb"
#    export SP_APPWRITE_KEY="standard_…"
#
#    # 2. Run:
#    curl -fsSL https://raw.githubusercontent.com/saistarayub-hash/stramingseparator/arena/01a0ba1a-stramingseparator/scripts/setup-vps.sh -o /tmp/sp-setup.sh
#    bash /tmp/sp-setup.sh
#
#  After it finishes, open http://<your-vps-ip>:8787 (or your domain).
# ==============================================================================
set -euo pipefail

APP_DIR="${APP_DIR:-/opt/streampilot}"
BRANCH="arena/01a0ba1a-stramingseparator"
REPO="https://github.com/saistarayub-hash/stramingseparator.git"

log()  { printf '\n\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m⚠ %s\033[0m\n' "$*"; }

# ---------------------------------------------------------------- deps
log "Installing system packages (curl/git/ca-certs)…"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y curl git ca-certificates gnupg

# ---------------------------------------------------------------- docker
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker…"
  curl -fsSL https://get.docker.com | sh
fi
if ! command -v docker >/dev/null 2>&1; then
  warn "Docker still unavailable — is curl working? Installing via apt fallback…"
  apt-get install -y docker.io
fi
systemctl enable --now docker

if ! docker compose version >/dev/null 2>&1; then
  log "Installing docker-compose plugin…"
  apt-get install -y docker-compose-plugin
fi

# ---------------------------------------------------------------- code
if [ -d "${APP_DIR}/.git" ]; then
  log "Updating StreamPilot (git pull)…"
  git -C "${APP_DIR}" fetch origin
  git -C "${APP_DIR}" checkout "${BRANCH}"
  git -C "${APP_DIR}" reset --hard "origin/${BRANCH}"
else
  log "Cloning StreamPilot…"
  if [ ! -d "${APP_DIR}" ]; then git clone "${REPO}" "${APP_DIR}"; fi
  git -C "${APP_DIR}" fetch origin
  git -C "${APP_DIR}" checkout "${BRANCH}"
fi

cd "${APP_DIR}"

# ---------------------------------------------------------------- .env
log "Writing .env (uses exported vars, else prompts)…"
PROJECT="${SP_APPWRITE_PROJECT:-}"
KEY="${SP_APPWRITE_KEY:-}"
if [ -z "${PROJECT}" ]; then read -rp "Appwrite Project ID: " PROJECT; fi
if [ -z "${KEY}" ]; then read -rsp "Appwrite API key: " KEY; echo; fi

# sensible fallback public URL for something always-on
[ -n "${SP_DOMAIN:-}" ] && APP_URL="https://${SP_DOMAIN}" || APP_URL="http://$(hostname -I | awk '{print $1}'):8787"

cat > .env <<EOF
# Generated by scripts/setup-vps.sh — git-ignored, keep private.
APPWRITE_ENDPOINT=https://nyc.cloud.appwrite.io/v1
APPWRITE_PROJECT_ID=${PROJECT}
APPWRITE_API_KEY=${KEY}

# YouTube OAuth (optional — setup in Google Cloud Console)
YOUTUBE_CLIENT_ID=${SP_YOUTUBE_ID:-}
YOUTUBE_CLIENT_SECRET=${SP_YOUTUBE_SECRET:-}
YOUTUBE_REDIRECT_URI=${SP_DOMAIN:+https://${SP_DOMAIN}/auth/youtube/callback}

# Twitch / Kick chat (optional)
TWITCH_CHANNEL=${SP_TWITCH_CHANNEL:-}
TWITCH_BOT_USER=${SP_TWITCH_BOT_USER:-}
TWITCH_BOT_OAUTH=${SP_TWITCH_BOT_OAUTH:-}
KICK_CHANNEL=${SP_KICK_CHANNEL:-}

SP_WHISPER_MODEL=${SP_WHISPER_MODEL:-small}
APP_URL=${APP_URL}
PORT=8787
EOF
chmod 600 .env
log "Credentials stored in ${APP_DIR}/.env (owner-only)."

# ---------------------------------------------------------------- run
log "Building & starting StreamPilot (first build takes a few minutes)…"
docker compose up -d --build
docker compose ps

log "Verifying…"
sleep 3
curl -fsS "http://localhost:8787/api/status" || warn "Health check not responding yet — run: docker compose logs -f"

# ---------------------------------------------------------------- firewall
log "Opening firewall ports (80/443/8787)…"
if command -v ufw >/dev/null 2>&1; then
  ufw allow 22/tcp || true
  ufw allow 8787/tcp || true
  ufw allow 80/tcp || true
  ufw allow 443/tcp || true
  ufw --force enable || true
fi

# ---------------------------------------------------------------- summary
IP="$(hostname -I | awk '{print $1}')"
printf '\n\033[1;32m✅ StreamPilot is live (free + always-on).\033[0m\n'
printf '   Open:  http://%s:8787\n' "${IP}"
[ -n "${SP_DOMAIN:-}" ] && printf '   Soon:  https://%s  (then APP_URL is already set)\n' "${SP_DOMAIN}"
printf '\n   Note: your Appwrite creds are in %s/.env — app auto-creates\n   the database/collections/bucket on first boot.\n' "${APP_DIR}"
